# Generated by Django 4.0.3 on 2022-03-26 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poke',
            name='type',
            field=models.CharField(choices=[('e', 'electric'), ('d', 'dragon'), ('f', 'fire'), ('g', 'ghost'), ('n', 'normal'), ('p', 'plant'), ('ps', 'psychic'), ('r', 'rock'), ('w', 'water')], max_length=10),
        ),
    ]
