# Generated by Django 4.0.3 on 2022-03-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_poke_user_alter_poke_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokeMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('e', 'electric'), ('d', 'dragon'), ('f', 'fire'), ('g', 'ghost'), ('n', 'normal'), ('p', 'plant'), ('ps', 'psychic'), ('r', 'rock'), ('w', 'water')], max_length=10)),
            ],
        ),
    ]
