# Generated by Django 4.0.3 on 2022-03-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pokemove'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='pokemoves',
            field=models.ManyToManyField(to='main_app.pokemove'),
        ),
    ]
