# Generated by Django 4.0.3 on 2022-03-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_poke_pokemoves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='type',
            field=models.CharField(choices=[('Electric', 'Electric'), ('Dragon', 'Dragon'), ('Fire', 'Fire'), ('Ghost', 'Ghost'), ('Normal', 'Normal'), ('Plant', 'Plant'), ('Psychic', 'Psychic'), ('Rock', 'Rock'), ('Water', 'Water')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pokemove',
            name='type',
            field=models.CharField(choices=[('Electric', 'Electric'), ('Dragon', 'Dragon'), ('Fire', 'Fire'), ('Ghost', 'Ghost'), ('Normal', 'Normal'), ('Plant', 'Plant'), ('Psychic', 'Psychic'), ('Rock', 'Rock'), ('Water', 'Water')], max_length=10),
        ),
    ]
